# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPrueba1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_prueba1(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    self.driver.set_window_size(1296, 696)
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("Admin")
    self.driver.find_element(By.NAME, "password").send_keys("admin123")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-main-menu-item-wrapper:nth-child(5) .oxd-text").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-header-container")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary:nth-child(1)").click()
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("oscar Andres Perez")
    self.driver.find_element(By.NAME, "middleName").send_keys("Test 45 Tester")
    self.driver.find_element(By.NAME, "lastName").send_keys("ignacio")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-select-text--arrow").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-select-option:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").send_keys("oscarandres@hotmail.com")
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div[2]/div[2]/div/div/form/div[3]/div/div[2]/div/div[2]/input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item > .oxd-input-group > div > .oxd-input--focus").send_keys("3214567894")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--success").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--success").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").send_keys("tester 34")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-autocomplete-text-input > input").send_keys("Joseph  ")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").send_keys("2024-05-11")
    element = self.driver.find_element(By.CSS_SELECTOR, ".bi-plus")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-textarea").send_keys("hired")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--success").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
  
